cmd_client.c: avoid possibility of truncated results from snprintf
cmdclient() in cmd_client.c may cause snprintf to return a truncated
result due to being passed an output buffer which is too small to
safely hold the maximal length result when setting up the final value
of arg_list.

The following warnings were generated by gcc 8:

 | src/lib/cmdserver/src/cmd_client.c: In function 'cmdclient':
 | src/lib/cmdserver/src/cmd_client.c:116:50: error: '%s' directive output may be truncated writing up to 32767 bytes into a region of size 32761 [-Werror=format-truncation=]
 |      snprintf(arg_list, sizeof(arg_list), "base64 %s\nexit\n", b64_buffer);
 |                                                   ^~           ~~~~~~~~~~
 | src/lib/cmdserver/src/cmd_client.c:116:5: note: 'snprintf' output between 14 and 32781 bytes into a destination of size 32768
 |      snprintf(arg_list, sizeof(arg_list), "base64 %s\nexit\n", b64_buffer);
 |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>