pjs: fix cast between incompatible function types for cb_out() callbacks
The following warnings were generated by gcc 8:

 | In file included from src/lib/pjs/inc/pjs_gen_c.h:27,
 |                  from src/lib/ovsdb/src/ovsdb_sync.c:47:
 | src/lib/pjs/inc/pjs_gen_c.h: In function 'rpc_response_from_json':
 | src/lib/pjs/inc/pjs_from_json.h:110:13: error: cast between incompatible function types from '_Bool (*)(struct rpc_response_error *, json_t *, _Bool,  char *)' {aka '_Bool (*)(struct rpc_response_error *, struct json_t *, _Bool,  char *)'} to '_Bool (*)(void *, json_t *, char *)' {aka '_Bool (*)(void *, struct json_t *, char *)'} [-Werror=cast-function-type]
 |              (pjs_sub_from_json_cb_t *)sub ## _from_json,                                \
 |              ^
 | src/lib/pjs/inc/pjs_from_json.h:42:5: note: in definition of macro 'PJS'
 |      __VA_ARGS__                                                                         \
 |      ^~~~~~~~~~~
 | src/lib/ovsdb/inc/ovsdb_jsonrpc.pjs.h:47:9: note: in expansion of macro 'PJS_SUB_Q'
 |          PJS_SUB_Q(error, rpc_response_error)    \
 |          ^~~~~~~~~
 | src/lib/ovsdb/inc/ovsdb_jsonrpc.pjs.h:50:51: note: in expansion of macro 'PJS_RPC_RS'
 |  #define PJS_GEN_TABLE PJS_RPC_RQ PJS_RPC_RS_ERROR PJS_RPC_RS
 |                                                    ^~~~~~~~~~
 | src/lib/pjs/inc/pjs_gen_c.h:28:1: note: in expansion of macro 'PJS_GEN_TABLE'
 |  PJS_GEN_TABLE
 |  ^~~~~~~~~~~~~

Reformatting the error slightly gives:

 | src/lib/pjs/inc/pjs_from_json.h:110:13: error: cast between incompatible function types from:
 |
 |  '_Bool (*)(struct rpc_response_error *, json_t *, _Bool,  char *)' {aka '_Bool (*)(struct rpc_response_error *, struct json_t *, _Bool,  char *)'} to
 |  '_Bool (*)(void *                     , json_t *,         char *)' {aka '_Bool (*)(void *                     , struct json_t *,         char *)'}
 |

ie the JPS macro is creating a function which requires 4 arguments,
but the function is then assigned to a function pointer type which
expects only 3 arguments ( pjs_sub_from_json_cb_t ).

The implication appears to be that upto now when cb_out() callbacks
have been called from pjs_sub_t_from_json(), the arguments have been
wrong - the NULL error message passed by pjs_sub_t_from_json() has
been interpretted by the JPS callback as setting "update" to false
and the error message pointer passed to the callback has been
undefined.

Signed-off-by: Andre McCurdy <armccurdy@gmail.com>